/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary-fixed-dim": "#a7c8ff",
        "surface-variant": "#d8e3fa",
        "on-tertiary-fixed-variant": "#434749",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffcca8",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#c4c7c9",
        "surface": "#f9f9ff",
        "on-tertiary-container": "#999c9e",
        "background": "#f9f9ff",
        "on-primary-fixed-variant": "#1f477b",
        "on-error": "#ffffff",
        "primary-container": "#0b437c",
        "tertiary": "#1b1f21",
        "inverse-surface": "#263142",
        "surface-container-highest": "#d8e3fa",
        "secondary-container": "#ffe0cc",
        "on-primary-fixed": "#001b3c",
        "surface-tint": "#3a5f94",
        "on-secondary-fixed-variant": "#cc6600",
        "outline-variant": "#c3c6d1",
        "on-tertiary": "#ffffff",
        "surface-container": "#e7eeff",
        "outline": "#737780",
        "secondary": "#ff9933",
        "on-error-container": "#93000a",
        "on-secondary-container": "#994c00",
        "on-primary": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container-high": "#dee8ff",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#a7c8ff",
        "on-tertiary-fixed": "#181c1e",
        "on-surface": "#111c2c",
        "on-secondary-fixed": "#331a00",
        "on-surface-variant": "#43474f",
        "tertiary-container": "#303436",
        "primary": "#0b437c",
        "inverse-on-surface": "#ebf1ff",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#ff9933",
        "on-background": "#111c2c",
        "surface-bright": "#f9f9ff",
        "on-primary-container": "#799dd6",
        "surface-dim": "#cfdaf1",
        "primary-fixed": "#d5e3ff",
        "tertiary-fixed": "#e0e3e5"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter": "24px",
        "sidebar-width": "280px",
        "stack-sm": "8px",
        "container-max": "1440px",
        "stack-lg": "32px",
        "margin-page": "40px",
        "unit": "8px",
        "stack-md": "16px"
      },
      "fontFamily": {
        "body-md": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "h1": ["Public Sans", "sans-serif"],
        "h3": ["Public Sans", "sans-serif"],
        "caption": ["Work Sans", "sans-serif"],
        "h2": ["Public Sans", "sans-serif"],
        "label-sm": ["Work Sans", "sans-serif"],
        "public-sans": ["Public Sans", "sans-serif"],
      },
      "fontSize": {
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "h1": ["40px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "h3": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "caption": ["12px", {"lineHeight": "1.2", "fontWeight": "400"}],
        "h2": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "label-sm": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
